theme: jekyll-theme-slate
title: Data Visualization
description: Assignments done from Karl Ho's Fall 2020 Data Visualization class at the University of Texas at Dallas. Together we explore a wide variety of topics in data and data science through study and application.
baseurl: /datavisualization
